# Generated by Django 3.0.8 on 2020-08-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='작성자')),
                ('contents', models.CharField(max_length=100, verbose_name='글제목')),
                ('texts', models.TextField(max_length=1000, verbose_name='글내용')),
                ('pdate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('like', models.IntegerField(default=0, verbose_name='추천')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20, verbose_name='댓글작성자')),
                ('reply', models.TextField(max_length=200, verbose_name='댓글')),
                ('reple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
