# Generated by Django 3.0.8 on 2020-08-06 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='pdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=200, verbose_name='댓글'),
        ),
    ]
