# Generated by Django 3.0.8 on 2020-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200806_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.CharField(max_length=200, verbose_name='댓글내용'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='writer',
            field=models.CharField(max_length=20, verbose_name='작성자'),
        ),
    ]
