# Generated by Django 3.0.8 on 2020-08-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200806_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdate',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pdate',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일'),
        ),
    ]
