# Generated by Django 3.0.8 on 2020-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200806_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlike',
            field=models.IntegerField(default=0, verbose_name='비추'),
        ),
    ]
