# Generated by Django 3.0.8 on 2020-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_unlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
    ]
