# Generated by Django 3.0.8 on 2020-08-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.EmailField(max_length=72, verbose_name='이메일'),
        ),
    ]
